//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.10 at 04:45:50 PM CET 
//


package eu.fbk.knowledgestore.populator.naf.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Raw }
     * 
     */
    public Raw createRaw() {
        return new Raw();
    }

    /**
     * Create an instance of {@link Nt }
     * 
     */
    public Nt createNt() {
        return new Nt();
    }

    /**
     * Create an instance of {@link Chunk }
     * 
     */
    public Chunk createChunk() {
        return new Chunk();
    }

    /**
     * Create an instance of {@link Span }
     * 
     */
    public Span createSpan() {
        return new Span();
    }

    /**
     * Create an instance of {@link OpinionHolder }
     * 
     */
    public OpinionHolder createOpinionHolder() {
        return new OpinionHolder();
    }

    /**
     * Create an instance of {@link Predicate }
     * 
     */
    public Predicate createPredicate() {
        return new Predicate();
    }

    /**
     * Create an instance of {@link ExternalReferences }
     * 
     */
    public ExternalReferences createExternalReferences() {
        return new ExternalReferences();
    }

    /**
     * Create an instance of {@link Role }
     * 
     */
    public Role createRole() {
        return new Role();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Terms }
     * 
     */
    public Terms createTerms() {
        return new Terms();
    }

    /**
     * Create an instance of {@link Term }
     * 
     */
    public Term createTerm() {
        return new Term();
    }

    /**
     * Create an instance of {@link Lp }
     * 
     */
    public Lp createLp() {
        return new Lp();
    }

    /**
     * Create an instance of {@link Tunits }
     * 
     */
    public Tunits createTunits() {
        return new Tunits();
    }

    /**
     * Create an instance of {@link NafHeader }
     * 
     */
    public NafHeader createNafHeader() {
        return new NafHeader();
    }

    /**
     * Create an instance of {@link FileDesc }
     * 
     */
    public FileDesc createFileDesc() {
        return new FileDesc();
    }

    /**
     * Create an instance of {@link Public }
     * 
     */
    public Public createPublic() {
        return new Public();
    }

    /**
     * Create an instance of {@link LinguisticProcessors }
     * 
     */
    public LinguisticProcessors createLinguisticProcessors() {
        return new LinguisticProcessors();
    }

    /**
     * Create an instance of {@link OpinionExpression }
     * 
     */
    public OpinionExpression createOpinionExpression() {
        return new OpinionExpression();
    }

    /**
     * Create an instance of {@link Factualitylayer }
     * 
     */
    public Factualitylayer createFactualitylayer() {
        return new Factualitylayer();
    }

    /**
     * Create an instance of {@link Factvalue }
     * 
     */
    public Factvalue createFactvalue() {
        return new Factvalue();
    }

    /**
     * Create an instance of {@link Sentiment }
     * 
     */
    public Sentiment createSentiment() {
        return new Sentiment();
    }

    /**
     * Create an instance of {@link Srl }
     * 
     */
    public Srl createSrl() {
        return new Srl();
    }

    /**
     * Create an instance of {@link Tree }
     * 
     */
    public Tree createTree() {
        return new Tree();
    }

    /**
     * Create an instance of {@link T }
     * 
     */
    public T createT() {
        return new T();
    }

    /**
     * Create an instance of {@link Edge }
     * 
     */
    public Edge createEdge() {
        return new Edge();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link Locations }
     * 
     */
    public Locations createLocations() {
        return new Locations();
    }

    /**
     * Create an instance of {@link Dates }
     * 
     */
    public Dates createDates() {
        return new Dates();
    }

    /**
     * Create an instance of {@link Coreferences }
     * 
     */
    public Coreferences createCoreferences() {
        return new Coreferences();
    }

    /**
     * Create an instance of {@link Coref }
     * 
     */
    public Coref createCoref() {
        return new Coref();
    }

    /**
     * Create an instance of {@link Opinion }
     * 
     */
    public Opinion createOpinion() {
        return new Opinion();
    }

    /**
     * Create an instance of {@link OpinionTarget }
     * 
     */
    public OpinionTarget createOpinionTarget() {
        return new OpinionTarget();
    }

    /**
     * Create an instance of {@link Deps }
     * 
     */
    public Deps createDeps() {
        return new Deps();
    }

    /**
     * Create an instance of {@link Dep }
     * 
     */
    public Dep createDep() {
        return new Dep();
    }

    /**
     * Create an instance of {@link Timex3 }
     * 
     */
    public Timex3 createTimex3() {
        return new Timex3();
    }

    /**
     * Create an instance of {@link Chunks }
     * 
     */
    public Chunks createChunks() {
        return new Chunks();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Wf }
     * 
     */
    public Wf createWf() {
        return new Wf();
    }

    /**
     * Create an instance of {@link Constituency }
     * 
     */
    public Constituency createConstituency() {
        return new Constituency();
    }

    /**
     * Create an instance of {@link ExternalRef }
     * 
     */
    public ExternalRef createExternalRef() {
        return new ExternalRef();
    }

    /**
     * Create an instance of {@link Entities }
     * 
     */
    public Entities createEntities() {
        return new Entities();
    }

    /**
     * Create an instance of {@link NAF }
     * 
     */
    public NAF createNAF() {
        return new NAF();
    }

    /**
     * Create an instance of {@link TimeExpressions }
     * 
     */
    public TimeExpressions createTimeExpressions() {
        return new TimeExpressions();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Opinions }
     * 
     */
    public Opinions createOpinions() {
        return new Opinions();
    }

}
