//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.10 at 04:45:50 PM CET 
//


package eu.fbk.knowledgestore.populator.naf.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opinionHolderOrOpinionTargetOrOpinionExpression"
})
@XmlRootElement(name = "opinion")
public class Opinion {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElements({
        @XmlElement(name = "opinion_holder", required = true, type = OpinionHolder.class),
        @XmlElement(name = "opinion_target", required = true, type = OpinionTarget.class),
        @XmlElement(name = "opinion_expression", required = true, type = OpinionExpression.class)
    })
    protected List<Object> opinionHolderOrOpinionTargetOrOpinionExpression;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the opinionHolderOrOpinionTargetOrOpinionExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opinionHolderOrOpinionTargetOrOpinionExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpinionHolderOrOpinionTargetOrOpinionExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpinionHolder }
     * {@link OpinionTarget }
     * {@link OpinionExpression }
     * 
     * 
     */
    public List<Object> getOpinionHolderOrOpinionTargetOrOpinionExpression() {
        if (opinionHolderOrOpinionTargetOrOpinionExpression == null) {
            opinionHolderOrOpinionTargetOrOpinionExpression = new ArrayList<Object>();
        }
        return this.opinionHolderOrOpinionTargetOrOpinionExpression;
    }

}
