//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 06:08:32 PM CEST 
//


package eu.fbk.knowledgestore.populator.naf.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import eu.fbk.knowledgestore.populator.naf.model.Srl;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nafHeader","raw","topics","text","terms","deps","chunks","entities","coreferences","constituency","srl","opinions","timeExpressions","factualitylayer","tunits","locations","dates","temporalRelations","causalRelations","markables","attribution","factualities"
})
@XmlRootElement(name = "NAF")
public class NAF {

    @XmlAttribute(name = "doc")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String doc;
    @XmlAttribute(name = "version")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;

    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace", required=true, name = "lang")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlLang;
    @XmlElement(name = "nafHeader", type = NafHeader.class)
    protected NafHeader nafHeader;
    @XmlElement(name = "raw", type = Raw.class)
    protected Raw raw; 
    @XmlElement(name = "topics", type = Topics.class)
    protected Topics topics;
    @XmlElement(name = "text", type = Text.class)
    protected Text text;
    @XmlElement(name = "terms", type = Terms.class)
    protected Terms terms;
    @XmlElement(name = "deps", type = Deps.class)
    protected Deps deps;
    @XmlElement(name = "chunks", type = Chunks.class)
    protected Chunks chunks;
    @XmlElement(name = "entities", type = Entities.class)
    protected Entities entities;
    @XmlElement(name = "coreferences", type = Coreferences.class)
    protected Coreferences coreferences;
    @XmlElement(name = "constituency", type = Constituency.class)
    protected Constituency constituency; 
    @XmlElement(name = "srl", type = Srl.class)
    protected Srl srl;
    @XmlElement(name = "opinions", type = Opinions.class)
    protected Opinions opinions;
    @XmlElement(name = "timeExpressions", type = TimeExpressions.class)
    protected TimeExpressions timeExpressions;
    @XmlElement(name = "factualitylayer", type = Factualitylayer.class)
    protected Factualitylayer factualitylayer; 
    @XmlElement(name = "tunits", type = Tunits.class)
    protected Tunits tunits;
    @XmlElement(name = "locations", type = Locations.class)
    protected Locations locations;
    @XmlElement(name = "dates", type = Dates.class)
    protected Dates dates;
    @XmlElement(name = "temporalRelations", type = TemporalRelations.class)
    protected TemporalRelations temporalRelations;
    @XmlElement(name = "causalRelations", type = CausalRelations.class)
    protected CausalRelations causalRelations;
    @XmlElement(name = "markables", type = Markables.class)
    protected Markables markables;
    @XmlElement(name = "attribution", type = Attribution.class)
    protected Attribution attribution;
    @XmlElement(name = "factualities", type = Factualities.class)
    protected Factualities factualities;
    
    /**
     * Gets the value of the doc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoc() {
        return doc;
    }

    /**
     * Sets the value of the doc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoc(String value) {
        this.doc = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the xmlLang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlLang() {
        return xmlLang;
    }

    /**
     * Sets the value of the xmlLang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlLang(String value) {
        this.xmlLang = value;
    }

	public NafHeader getNafHeader() {
		return nafHeader;
	}

	public void setNafHeader(NafHeader nafHeader) {
		this.nafHeader = nafHeader;
	}

	public Raw getRaw() {
		return raw;
	}

	public void setRaw(Raw raw) {
		this.raw = raw;
	}

	public Topics getTopics() {
		if(topics==null)
			topics = new Topics();
		return topics;
	}

	public void setTopics(Topics topics) {
		this.topics = topics;
	}

	public Text getText() {
		return text;
	}

	public void setText(Text text) {
		this.text = text;
	}

	public Terms getTerms() {
		return terms;
	}

	public void setTerms(Terms terms) {
		this.terms = terms;
	}

	public Deps getDeps() {
		if(deps==null)
			deps = new Deps();
		return deps;
	}

	public void setDeps(Deps deps) {
		this.deps = deps;
	}

	public Chunks getChunks() {
		if(chunks==null)
			chunks = new Chunks();
		return chunks;
	}

	public void setChunks(Chunks chunks) {
		this.chunks = chunks;
	}

	public Entities getEntities() {
		if(entities==null)
			entities = new Entities();
		return entities;
	}

	public void setEntities(Entities entities) {
		this.entities = entities;
	}

	public Coreferences getCoreferences() {
		if(coreferences==null)
			coreferences = new Coreferences();
		return coreferences;
	}

	public void setCoreferences(Coreferences coreferences) {
		this.coreferences = coreferences;
	}

	public Constituency getConstituency() {
		if(constituency==null)
			constituency = new Constituency();
		return constituency;
	}

	public void setConstituency(Constituency constituency) {
		this.constituency = constituency;
	}

	public Srl getSrl() {
		if(srl==null)
			srl = new Srl();
		return srl;
	}

	public void setSrl(Srl srl) {
		this.srl = srl;
	}

	public Opinions getOpinions() {
		if(opinions==null)
			opinions = new Opinions();
		return opinions;
	}

	public void setOpinions(Opinions opinions) {
		this.opinions = opinions;
	}

	public TimeExpressions getTimeExpressions() {
		if(timeExpressions==null)
			timeExpressions = new TimeExpressions();
		return timeExpressions;
	}

	public void setTimeExpressions(TimeExpressions timeExpressions) {
		this.timeExpressions = timeExpressions;
	}

	public Factualitylayer getFactualitylayer() {
		if(factualitylayer==null)
			factualitylayer = new Factualitylayer();
		return factualitylayer;
	}

	public void setFactualitylayer(Factualitylayer factualitylayer) {
		this.factualitylayer = factualitylayer;
	}

	public Tunits getTunits() {
		if(tunits==null)
			tunits = new Tunits();
		return tunits;
	}

	public void setTunits(Tunits tunits) {
		this.tunits = tunits;
	}

	public Locations getLocations() {
		if(locations==null)
			locations = new Locations();
		return locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	public Dates getDates() {
		if(dates==null)
			dates = new Dates();
		return dates;
	}

	public void setDates(Dates dates) {
		this.dates = dates;
	}

	public TemporalRelations getTemporalRelations() {
		if(temporalRelations==null)
			temporalRelations = new TemporalRelations();
		return temporalRelations;
	}

	public void setTemporalRelations(TemporalRelations temporalRelations) {
		this.temporalRelations = temporalRelations;
	}

	public CausalRelations getCausalRelations() {
		if(causalRelations==null)
			causalRelations = new CausalRelations();
		return causalRelations;
	}

	public void setCausalRelations(CausalRelations causalRelations) {
		this.causalRelations = causalRelations;
	}

	public Markables getMarkables() {
		if(markables==null)
			markables = new Markables();
		return markables;
	}

	public void setMarkables(Markables markables) {
		this.markables = markables;
	}

	public Attribution getAttribution() {
		if(attribution==null)
			attribution = new Attribution();
		return attribution;
	}

	public void setAttribution(Attribution attribution) {
		this.attribution = attribution;
	}

	public Factualities getFactualities() {
		if(factualities==null)
			factualities = new Factualities();
		return factualities;
	}

	public void setFactualities(Factualities factualities) {
		this.factualities = factualities;
	}
    
    

}
