//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.10 at 04:45:50 PM CET 
//


package eu.fbk.knowledgestore.populator.naf.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "sentiment")
public class Sentiment {

    @XmlAttribute(name = "resource")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String resource;
    @XmlAttribute(name = "polarity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String polarity;
    @XmlAttribute(name = "strength")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String strength;
    @XmlAttribute(name = "subjectivity")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subjectivity;
    @XmlAttribute(name = "sentiment_semantic_type")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sentimentSemanticType;
    @XmlAttribute(name = "sentiment_product_feature")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sentimentProductFeature;
    @XmlAttribute(name = "sentiment_modifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sentimentModifier;
    @XmlAttribute(name = "sentiment_marker")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String sentimentMarker;

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the polarity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolarity() {
        return polarity;
    }

    /**
     * Sets the value of the polarity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolarity(String value) {
        this.polarity = value;
    }

    /**
     * Gets the value of the strength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrength() {
        return strength;
    }

    /**
     * Sets the value of the strength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrength(String value) {
        this.strength = value;
    }

    /**
     * Gets the value of the subjectivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectivity() {
        return subjectivity;
    }

    /**
     * Sets the value of the subjectivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectivity(String value) {
        this.subjectivity = value;
    }

    /**
     * Gets the value of the sentimentSemanticType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentimentSemanticType() {
        return sentimentSemanticType;
    }

    /**
     * Sets the value of the sentimentSemanticType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentimentSemanticType(String value) {
        this.sentimentSemanticType = value;
    }

    /**
     * Gets the value of the sentimentProductFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentimentProductFeature() {
        return sentimentProductFeature;
    }

    /**
     * Sets the value of the sentimentProductFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentimentProductFeature(String value) {
        this.sentimentProductFeature = value;
    }

    /**
     * Gets the value of the sentimentModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentimentModifier() {
        return sentimentModifier;
    }

    /**
     * Sets the value of the sentimentModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentimentModifier(String value) {
        this.sentimentModifier = value;
    }

    /**
     * Gets the value of the sentimentMarker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentimentMarker() {
        return sentimentMarker;
    }

    /**
     * Sets the value of the sentimentMarker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentimentMarker(String value) {
        this.sentimentMarker = value;
    }

}
