//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 06:08:32 PM CEST 
//


package eu.fbk.knowledgestore.populator.naf.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "span"
})
@XmlRootElement(name = "timex3")
public class Timex3 {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "beginPoint")
    @XmlIDREF
    protected Object beginPoint;
    @XmlAttribute(name = "endPoint")
    @XmlIDREF
    protected Object endPoint;
    @XmlAttribute(name = "quant")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String quant;
    @XmlAttribute(name = "freq")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String freq;
    @XmlAttribute(name = "functionInDocument")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String functionInDocument;
    @XmlAttribute(name = "temporalFunction")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String temporalFunction;
    @XmlAttribute(name = "value")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String value;
    @XmlAttribute(name = "valueFromFunction")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String valueFromFunction;
    @XmlAttribute(name = "mod")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String mod;
    @XmlAttribute(name = "anchorTimeID")
    @XmlIDREF
    protected Object anchorTimeID;
    
    @XmlElement(name = "span", type = Span.class)
    protected Span span;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the beginPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getBeginPoint() {
        return beginPoint;
    }

    /**
     * Sets the value of the beginPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setBeginPoint(Object value) {
        this.beginPoint = value;
    }

    /**
     * Gets the value of the endPoint property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEndPoint() {
        return endPoint;
    }

    /**
     * Sets the value of the endPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEndPoint(Object value) {
        this.endPoint = value;
    }

    /**
     * Gets the value of the quant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuant() {
        return quant;
    }

    /**
     * Sets the value of the quant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuant(String value) {
        this.quant = value;
    }

    /**
     * Gets the value of the freq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreq() {
        return freq;
    }

    /**
     * Sets the value of the freq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreq(String value) {
        this.freq = value;
    }

    /**
     * Gets the value of the functionInDocument property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionInDocument() {
        return functionInDocument;
    }

    /**
     * Sets the value of the functionInDocument property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionInDocument(String value) {
        this.functionInDocument = value;
    }

    /**
     * Gets the value of the temporalFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemporalFunction() {
        return temporalFunction;
    }

    /**
     * Sets the value of the temporalFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemporalFunction(String value) {
        this.temporalFunction = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the valueFromFunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueFromFunction() {
        return valueFromFunction;
    }

    /**
     * Sets the value of the valueFromFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueFromFunction(String value) {
        this.valueFromFunction = value;
    }

    /**
     * Gets the value of the mod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMod() {
        return mod;
    }

    /**
     * Sets the value of the mod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMod(String value) {
        this.mod = value;
    }

    /**
     * Gets the value of the anchorTimeID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAnchorTimeID() {
        return anchorTimeID;
    }

    /**
     * Sets the value of the anchorTimeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAnchorTimeID(Object value) {
        this.anchorTimeID = value;
    }

	public Span getSpan() {
		if(span==null)
			span = new Span();
		return span;
	}

	public void setSpan(Span span) {
		this.span = span;
	}

 

}
